### PR TITLE
Support Python 3.9

### PR DESCRIPTION
**Pull request by candrikos**
@terencehonles has updated our transifex-client to use python3 successfully. Something did not work into our merging pipeline (appveyor) thus I created that PR as a workaround to unblock the process.

### CODE REVIEW

**Comment by terencehonles** [comment]
It really looks like appveyor might be building but is not updating GitHub https://ci.appveyor.com/project/transifex/transifex-client/builds/35855608

**Review by fathineos — DISMISSED** [review]
LGTM

**Review by Diontsoumas — APPROVED** [review]
LGTM. @terencehonles thanks a lot for your contribution, it seems that appveyor's communication with Github is broken during the last few days. We will investigate this properly, in the meantime I have disabled the status checks and merging this PR. Again, thanks for your time!

**Comment by Diontsoumas** [comment]
@terencehonles we will release a new version of the client first thing tomorrow in the morning

**Comment by terencehonles** [comment]
> @terencehonles we will release a new version of the client first thing tomorrow morning

Cool, thanks for the update!

**Pull request merged**
