### PR TITLE
Support proxy basic auth

### PR DESCRIPTION
**Pull request by arnaud-morvan**

### CODE REVIEW

**Comment by ebelo** [comment]
@SofiaMargariti our users would need an official release. The latest release is from Feb. Would you be so kind to tell us about the next release date? cc @jwkaltz

**Comment by samuelchan22** [comment]
@ebelo @jwkaltz We're aiming for some time in October for our next release, along with a few other changes currently on our roadmap.

**Comment by samuelchan22** [comment]
@ebelo @jwkaltz We released a new version of the client today (v0.12.5) which lets you work behind an authenticated proxy with Basic auth. Give it a try and let us know how how everything's working for you.

**Comment by jwkaltz** [comment]
@samuelchan22 thanks, it is working fine now.

**Pull request merged**
