### PR TITLE
support standard tx urls

### LINKED ISSUE #106: tx set should accept URLs such as transifex.com/org_slug/project_slug
Right now it only accepts `/projects/p/project_slug`.

```
$ tx set --auto-remote https://www.transifex.com/transifex/transifex
Auto configuring local project from remote URL...
Exception: tx: Malformed url given. Please refer to our docs: http://bit.ly/txcconfig
```

### PR DESCRIPTION
**Pull request by kouk**
Fixes #106

### CODE REVIEW

**Comment by kouk** [comment]
@diegobz review time ;-)

**Comment by diegobz** [comment]
@kouk Can we have tests for the CI tools? :)

**Comment by kouk** [comment]
@diegboz i'll try and find some time this week.

**Comment by dimoschi** [comment]
@kouk & @diegobz I checked this, and it works. Should I merge it?

**Comment by kouk** [comment]
@dimoschi we need to include this in the next release for sure. I would
wait until we know when we are going to do that to merge this.

--
Konstantinos Koukopoulos, Software Engineer
mailto:kouk@transifex.com - tel:+306948630066

**Comment by dimoschi** [comment]
@tabac This PR makes it possible to use the latest URL structure `<www.transifex.com/<organization_slug>/<project_slug>` of Transifex rather than limiting the URLs to the old structure `www.transifex.com/projects/p/<project_slug>`

**Comment by kouk** [comment]
@tabac lgtm

**Pull request merged**
