### PR TITLE
test with optional dependencies

### PR DESCRIPTION
**Pull request by kouk**
@dimoschi in order for the SSL warning to go away, as we discussed, this change is necessary in the client.

### CODE REVIEW

**Comment by kouk** [comment]
@dimoschi bump

**Comment by dimoschi** [comment]
@kouk I totally forgot about this. I did test it and it works, however I didn't have any issues even without it. Maybe I'm missing something here, so I could use your help.

**Comment by dimoschi** [comment]
Also I forgot, it seems that this PR will merge something into another branch `six_input` which is already merged and not `master`

**Comment by dimoschi** [comment]
@kouk merged directly to master. So closing it.

**Pull request closed without merging**
