### PR TITLE
use input from six.moves. Fixes: #123

### PR DESCRIPTION
**Pull request by kouk**
@tabac please review

### CODE REVIEW

**Comment by diegobz** [comment]
@kouk I guess we need to fix something in the PO files here https://github.com/diegobz/txci.

We should also probably move that repo under the transifex org in github.

**Comment by kouk** [comment]
@tabac I switched to an updated test repo for the tests that now works correctly. Could you merge?

**Comment by SofiaMargariti** [comment]
I tested this and looks good.. but the CI is still failing

**Comment by dimoschi** [comment]
@SofiaMargariti @kouk @diegobz The problem is with a translation file in Transifex, which you can find [here](https://www.transifex.com/txci/txci/win-Python27/)

**Comment by kouk** [comment]
@SofiaMargariti someone (you?) fixed the build! Huzzah!

**Pull request merged**
