### PR TITLE
Fix issues with zip type formats (docx, xlsx).

### PR DESCRIPTION
**Pull request by ollandos**
Description: Look at title.

Jira ticket: https://transifex.atlassian.net/browse/TX-5919

### CODE REVIEW

**Comment by dimoschi** [comment]
@ollandos I verified it with DOCX and XLSX files and it's working. @diegobz should I merge?

**Comment by tabac** [comment]
Add a few tests plz.

**Comment by surkova** [comment]
https://github.com/transifex/transifex-client/pull/119 would be great to merge my PR first :)

**Comment by tabac** [comment]
Will do just after we make a release, thanks!

**Comment by surkova** [comment]
@tabac I have rebased my branch on top of this work.

**Pull request merged**
