### PR TITLE
Support Python 3.8

### PR DESCRIPTION
**Pull request by terencehonles**

### CODE REVIEW

**Comment by terencehonles** [comment]
Created PR to fix the docker image you are using randomknowledge/docker-pyenv-tox#4

**Comment by terencehonles** [comment]
The new docker image seems to run tox correctly and the tests pass, but I am having problems with the code in `./contrib/test_build.sh` I saw this locally and am not sure if I need to change something else.

**Comment by rigaspapas** [comment]
Python 3.8 is not yet available to pyenv. CI fails with the following message `python-build: definition not found: 3.8.0`

**Comment by terencehonles** [comment]
@rigaspapas yes, I'm aware that's the PR I listed in https://github.com/transifex/transifex-client/pull/266#issuecomment-549082695

**Comment by terencehonles** [comment]
@rigaspapas it looks like the PR I submitted was merged and the docker image was updated. I amended my commit to kick off circleci again.

**Comment by terencehonles** [comment]
@rigaspapas do you know if there's something that should be fixed to get the circle CI check to pass? I believe this PR is good to merge now, but it's still showing red.

**Comment by deathbird** [comment]
@terencehonles Thank you for your contribution! To overcome the hurdle of environment variables not being copied across forked repositories we continue your PR on [#269 ] which was merged. Thanks again!

**Pull request closed without merging**
