### PR TITLE
Add authenticated proxy support

### LINKED ISSUE #166: using tx behind an authenticated proxy
Since https://github.com/transifex/transifex-client/pull/130 it is possible to use tx behing a proxy. But there is no way yet to get it work behind an authenticated proxy with Basic auth and username/password.

You can only submit host and port: https://docs.transifex.com/client/introduction#help

Thank you very much for any help or new feature on this issue.

### PR DESCRIPTION
**Pull request by sbrunner**
fix #166

### CODE REVIEW

**Comment by sbrunner** [comment]
The CI is now OK :-)

**Comment by ebelo** [comment]
@ChrsMark can you pls review?

**Comment by arnaud-morvan** [comment]
Missed this, I've openned slightly different implementation here : https://github.com/transifex/transifex-client/pull/170, without removing the useragent header.

**Comment by sbrunner** [comment]
Defining the same header in the ProxyManager and in the request don't have any sense, one of the can be removed without affecting the final request...

**Comment by sbrunner** [comment]
What about this?

**Comment by sbrunner** [comment]
Up @diegobz @glezos @ChrsMark @SofiaMargariti

**Comment by SofiaMargariti** [comment]
It seems that https://github.com/transifex/transifex-client/pull/170 has been merge, so I am closing this one.

**Pull request closed without merging**
